FROM golang:1.9-alpine3.7

ADD . /go/src/github.com/src-d/code-annotation
WORKDIR /go/src/github.com/src-d/code-annotation

#RUN sh ./scripts/install.sh
RUN apk --update upgrade
RUN apk add --no-cache \
    bash make curl git \
    ca-certificates build-base \
    libxml2-dev protobuf \
    yarn

RUN make prepare-build
RUN make packages

RUN cp build/bin/* /bin/

ENTRYPOINT ["/bin/server"]
